### ISSUE TITLE
Remove duplicate repository

### ISSUE THREAD

**Issue by noltron000** [Make-School-Courses/CS-1.3-Core-Data-Structures#2]
There are two duplicate repos on Make School's github; one is no longer maintained.
- [old repo](https://github.com/Make-School-Courses/CS-3-Core-Data-Structures)
- [new repo](https://github.com/Make-School-Courses/CS-1.3-Core-Data-Structures)

I made the mistake of forking the old repo early on. I recently went through the process of changing my fork's origin to the maintained repo new one so I could retrieve any current and future updates. Furthermore, this issue could lead to potential discrepancies and confusion on a students' side in the future, for example on any assignments that have been or will be changed.

There are likely others who made this same mistake. I recommend deleting—or at the very least, archiving—the old repo to avoid any problems in the future.

**Comment by ibirnam** [comment]
@noltron000 - we'll look into what we can do, but curious how you got to that old repo? I don't see it linked anywhere in the CS 1.3 repo, but want to make sure there's not a link to the old repo out there that needs to be cut

**Comment by noltron000** [comment]
I got to this repository by checking Make School's Github account directly, meaning there shouldn't be a broken link floating around.

**Comment by ibirnam** [comment]
@noltron000 - got it. I went through and renamed that repo to note that it's archived and no longer maintained. It'll still stick around, as there's material in there we may want to incorporate into our current classes, but that'll happen at a later date.

For now though, that repo, as well as all other old repos in the CS, BEW, FEW, MOB, and DS tracks, so there should be less confusion in finding the right one to use.

Thanks for pointing this out!
